language: r
cache: packages
r: 
  - release
  - 3.3
  - 3.4 

dist: xenial
warnings_are_errors: true
r_check_args: --no-tests --as-cran --no-manual

env:
  - NOT_CRAN=true

apt_packages:
  - libgsl-dev

r_packages:
  - gsl
  - R.rsp
  - covr

after_success:
  - travis_wait 60 Rscript -e 'covr::codecov()'
